services:
  backend:
    build: ./backend
    container_name: iweb-backend
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Required to manage host containers
    environment:
      - PORT=8000
    ports:
      - "8026:8000"

  frontend:
    build: ./frontend
    container_name: iweb-frontend
    restart: unless-stopped
    ports:
      - "3026:3000"
    environment:
      - BACKEND_URL=http://localhost:8026
    depends_on:
      - backend
